kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: B3fiERuABPQp9lakIdtigfCkfXH6zOcK32a0Y7+fXTY=
      - identity: {}
